includes:
  - https://github.ibm.com/cloud-docs/watson
  - https://github.ibm.com/cloud-docs/overview
  - https://github.ibm.com/cloud-docs/cloud-foundry-public
  - https://github.ibm.com/cloud-docs/resources
  - https://github.ibm.com/cloud-docs/account